# Example code-cop configuration file
# This file defines code quality metrics and thresholds

defaults:
  max_cyclomatic_complexity: 10
  min_maintainability_index: 50
  max_halstead_volume: 1000
  max_halstead_difficulty: 10
  max_halstead_effort: 10000
  max_cognitive_complexity: 15

languages:
  - name: python
    extensions:
      - .py
    metrics:
      - type: cyclomatic_complexity
        threshold: 10
        comparison: "<="
      - type: maintainability_index
        threshold: 50
        comparison: ">="
      - type: halstead_volume
        threshold: 1000
        comparison: "<="
      - type: halstead_difficulty
        threshold: 10
        comparison: "<="
      - type: halstead_effort
        threshold: 10000
        comparison: "<="
      - type: cognitive_complexity
        threshold: 15
        comparison: "<="
        enabled: false  # Requires complexipy

ignore_patterns:
  - "**/test_*.py"
  - "**/*_test.py"
  - "**/tests/**"
  - "**/__pycache__/**"
  - "**/.pytest_cache/**"