name: Tests

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  quick-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Run quick checks
      run: |
        ruff check code_cop tests
        black --check code_cop tests
        mypy code_cop tests || true  # Allow mypy to fail initially
        pytest -v || true  # Allow tests to fail initially